spring.application.name=eureka-server
server.port=${PORT:8761}

# En Railway (Standalone), el servidor Eureka no necesita registrarse consigo mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=staging-eureka-server
# Volvemos a activar la auto-preservación para mayor estabilidad
eureka.server.enable-self-preservation=true
eureka.server.renewal-percent-threshold=0.85