spring.application.name=eureka-server
server.port=${PORT:8761}

# En entornos distribuidos, podrías querer tener varios Eurekas (Peer Awareness)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=staging-eureka-server
|
# Volvemos a activar la auto-preservación para mayor estabilidad
eureka.server.enable-self-preservation=true
eureka.server.renewal-percent-threshold=0.85