# APPLICATION METADATA
spring.application.name=msvc-webhooks
server.port=8002


# DATABASE CONFIGURATION (PRUEBA LOCAL DIRECTA)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LOGGING DEBUG (PARA DETECTAR ERRORES DE CONEXIÓN)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.datasource=DEBUG

# --- OTRAS CONFIGURACIONES (COMENTADAS) ---
 springdoc.api-docs.path=/v3/api-docs
 springdoc.swagger-ui.path=/swagger-ui.html

 # Eureka Configuration
eureka.client.service-url.defaultZone=https://eureka-server-staging-76f2.up.railway.app/eureka
eureka.instance.prefer-ip-address=true

# RabbitMQ Configuration

spring.rabbitmq.host=${rabbitmq-pay-bridge.RAILWAY_INTERNAL_DOMAIN}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${rabbitmq-pay-bridge.RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${rabbitmq-pay-bridge.RABBITMQ_DEFAULT_PASS}

# Messaging SDK Generic Configuration
messaging.sdk.rabbit.queue-name=notification.queue
messaging.sdk.rabbit.exchange-name=notification.exchange
messaging.sdk.rabbit.routing-key=notification.payment.received
messaging.sdk.rabbit.dead-letter-exchange=notification.exchange.dlx
messaging.sdk.rabbit.dead-letter-routing-key=notification.dead.letter

# ==========================================
# SPRING ACTUATOR & HEALTH CHECKS
# ==========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=true

# BNC Webhook Security (V2.0)
bnc.webhook.api-key=bnc-secure-key-2026
bnc.webhook.user=bnc_user
bnc.webhook.password=bnc_pass_2026
bnc.webhook.jwt-secret=bnc_jwt_secret_key_fixed_for_demo